CREATE TABLE [dbo].[CAD_CONTA_BANCO] (
    [ID_CONTA_BANCO]        INT          IDENTITY (1, 1) NOT NULL,
    [DESCRICAO_CONTA_BANCO] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_CAD_CONTA_BANCO] PRIMARY KEY CLUSTERED ([ID_CONTA_BANCO] ASC)
);

