CREATE TABLE [dbo].[CAD_FORNECEDOR] (
    [ID_FORNECEDOR]             INT           IDENTITY (1, 1) NOT NULL,
    [NOME_FORNECEDOR]           VARCHAR (200) NOT NULL,
    [TIPO_FORNECEDOR]           CHAR (1)      NOT NULL,
    [FANTASIA_FORNECEDOR]       VARCHAR (200) NULL,
    [CPF_CNPJ_FORNECEDOR]       VARCHAR (18)  NOT NULL,
    [INSC_MUNICIPAL_FORNECEDOR] VARCHAR (15)  NULL,
    [INSC_ESTADUAL_FORNECEDOR]  VARCHAR (15)  NULL,
    [FONE_FORNECEDOR_1]         VARCHAR (15)  NOT NULL,
    [FONE_FORNECEDOR_2]         VARCHAR (15)  NULL,
    [EMAIL_FORNECEDOR]          VARCHAR (30)  NULL,
    [CEP_FORNECEDOR]            VARCHAR (9)   NOT NULL,
    [ENDERECO_FORNECEDOR]       VARCHAR (100) NOT NULL,
    [BAIRRO_FORNECEDOR]         VARCHAR (50)  NOT NULL,
    [CIDADE_FORNECEDOR]         VARCHAR (50)  NOT NULL,
    [UF]                        VARCHAR (2)   NOT NULL,
    [COMPLEMENTO_FORNECEDOR]    VARCHAR (20)  NULL,
    [DATA_INCLUSAO_FORNECEDOR]  DATETIME      NOT NULL,
    [DATA_ALTERACAO_FORNECEDOR] DATETIME      NULL,
    [NUMERO_FORNECEDOR]         VARCHAR (10)  NULL,
    CONSTRAINT [PK_CAD_FORNECEDOR] PRIMARY KEY CLUSTERED ([ID_FORNECEDOR] ASC)
);

