CREATE TABLE [dbo].[MOV_CONTA_PAGAR] (
    [ID_CONTA_PAGAR]         INT           IDENTITY (1, 1) NOT NULL,
    [CODIGO_FORNECEDOR]      INT           NOT NULL,
    [NUMERO_DOCUMENTO_PAGAR] VARCHAR (20)  NULL,
    [DATA_EMISSAO_PAGAR]     DATETIME      NOT NULL,
    [VALOR_CONTA_PAGAR]      FLOAT (53)    NOT NULL,
    [STATUS_CONTA_PAGAR]     CHAR (1)      NOT NULL,
    [OBS_CONTA_PAGAR]        VARCHAR (400) NULL,
    CONSTRAINT [PK_MOV_CONTA_PAGAR] PRIMARY KEY CLUSTERED ([ID_CONTA_PAGAR] ASC),
    CONSTRAINT [FK_MOV_CONTA_PAGAR_CAD_FORNECEDOR] FOREIGN KEY ([CODIGO_FORNECEDOR]) REFERENCES [dbo].[CAD_FORNECEDOR] ([ID_FORNECEDOR])
);

