CREATE TABLE [dbo].[MOV_CONTA_RECEBER_ITEM] (
    [ID_MOV_CONTA_ITEM]       INT        IDENTITY (1, 1) NOT NULL,
    [CODIGO_CONTA_RECEBER]    INT        NOT NULL,
    [CODIGO_CONTA_BANCO]      INT        NOT NULL,
    [VALOR_PARCELA_RECEBER]   FLOAT (53) NOT NULL,
    [DATA_PAGAMENTO_RECEBER]  DATETIME   NOT NULL,
    [DATA_VENCIMENTO_RECEBER] DATETIME   NOT NULL,
    [NUMERO_PARCELA_RECEBER]  INT        NOT NULL,
    CONSTRAINT [PK_MOV_CONTA_RECEBER_ITEM] PRIMARY KEY CLUSTERED ([ID_MOV_CONTA_ITEM] ASC),
    CONSTRAINT [FK_MOV_CONTA_RECEBER_ITEM_CAD_CONTA_BANCO] FOREIGN KEY ([CODIGO_CONTA_BANCO]) REFERENCES [dbo].[CAD_CONTA_BANCO] ([ID_CONTA_BANCO]),
    CONSTRAINT [FK_MOV_CONTA_RECEBER_ITEM_MOV_CONTA_RECEBER] FOREIGN KEY ([CODIGO_CONTA_RECEBER]) REFERENCES [dbo].[MOV_CONTA_RECEBER] ([ID_CONTA_RECEBER])
);

