CREATE TABLE [dbo].[MOV_CONTA_RECEBER] (
    [ID_CONTA_RECEBER]         INT           IDENTITY (1, 1) NOT NULL,
    [CODIGO_CLIENTE]           INT           NOT NULL,
    [NUMERO_DOCUMENTO_RECEBER] VARCHAR (20)  NULL,
    [DATA_EMISSAO_RECEBER]     DATETIME      NOT NULL,
    [VALOR_CONTA_RECEBER]      FLOAT (53)    NOT NULL,
    [STATUS_CONTA_RECEBER]     CHAR (1)      NOT NULL,
    [OBS_CONTA_RECEBER]        VARCHAR (400) NULL,
    CONSTRAINT [PK_MOV_CONTA_RECEBER] PRIMARY KEY CLUSTERED ([ID_CONTA_RECEBER] ASC),
    CONSTRAINT [FK_MOV_CONTA_RECEBER_CAD_CLIENTE] FOREIGN KEY ([CODIGO_CLIENTE]) REFERENCES [dbo].[CAD_CLIENTE] ([ID_CLIENTE])
);

