


-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[PR_NOVO_FORNECEDOR] 
	@NOME_FORNECEDOR VARCHAR(200),
	@TIPO_FORNECEDOR CHAR(1),
	@FANTASIA_FORNECEDOR VARCHAR(200) = NULL,
	@CPF_CNPJ_FORNECEDOR VARCHAR(18),
	@INSC_MUNICIPAL_FORNECEDOR VARCHAR(15) = NULL,
	@INSC_ESTADUAL_FORNECEDOR VARCHAR(15) = NULL,
	@FONE_FORNECEDOR_1 VARCHAR(15),
	@FONE_FORNECEDOR_2 VARCHAR(15) = NULL,
	@EMAIL_FORNECEDOR VARCHAR(30) =NULL,
	@CEP_FORNECEDOR VARCHAR(9),
	@ENDERECO_FORNECEDOR VARCHAR(100),
	@BAIRRO_FORNECEDOR VARCHAR(50),
	@CIDADE_FORNECEDOR VARCHAR(50),
	@UF_FORNECEDOR VARCHAR(2),
	@COMPLEMENTO_FORNECEDOR VARCHAR(20) = NULL,
	@DATA_ALTERACAO_FORNECEDOR DATETIME = NULL,
	@NUMERO_FORNECEDOR VARCHAR(10) = NULL

AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	INSERT INTO CAD_FORNECEDOR (
		NOME_FORNECEDOR,
		TIPO_FORNECEDOR,
		FANTASIA_FORNECEDOR,
		CPF_CNPJ_FORNECEDOR,
		INSC_MUNICIPAL_FORNECEDOR,
		INSC_ESTADUAL_FORNECEDOR,
		FONE_FORNECEDOR_1,
		FONE_FORNECEDOR_2,
		EMAIL_FORNECEDOR,
		CEP_FORNECEDOR,
		ENDERECO_FORNECEDOR,
		BAIRRO_FORNECEDOR,
		CIDADE_FORNECEDOR,
		UF,
		COMPLEMENTO_FORNECEDOR,
		DATA_INCLUSAO_FORNECEDOR,
		DATA_ALTERACAO_FORNECEDOR,
		NUMERO_FORNECEDOR)
	VALUES (
		@NOME_FORNECEDOR,
		@TIPO_FORNECEDOR,
		@FANTASIA_FORNECEDOR,
		@CPF_CNPJ_FORNECEDOR,
		@INSC_MUNICIPAL_FORNECEDOR,
		@INSC_ESTADUAL_FORNECEDOR,
		@FONE_FORNECEDOR_1,
		@FONE_FORNECEDOR_2,
		@EMAIL_FORNECEDOR,
		@CEP_FORNECEDOR,
		@ENDERECO_FORNECEDOR,
		@BAIRRO_FORNECEDOR,
		@CIDADE_FORNECEDOR,
		@UF_FORNECEDOR,
		@COMPLEMENTO_FORNECEDOR,
		GETDATE(),
		@DATA_ALTERACAO_FORNECEDOR,
		@NUMERO_FORNECEDOR);


END